#
# plugin settings
#
name: KuroBase
version: ${project.version}
main: host.kuro.kurobase.KuroBase
api-version: 1.15
authors: [kuro-123]
description: Base plugin for 123 server culture spigot
website: http://kuro.host/wordpress/
depend:
  - KuroDiscord
