name: KuroBase
version: ${project.version}
main: host.kuro.kurobase
api-version: 1.15.2
authors: [kuro-123]
description: Base plugin for 123 server culture spigot
website: http://kuro.host/wordpress/

commands:
