#
# plugin settings
#
name: KuroBase
version: ${project.version}
main: host.kuro.kurobase.KuroBase
api-version: 1.15
authors: [kuro-123]
description: Base plugin for 123 server culture spigot
website: http://kuro.host/
depend:
  - KuroDiscord

commands:
  list:
    description: オンラインプレイヤーをリスト表示します
    usage: /list
    aliases: [li]
  name:
    description: ニックネーム登録ができます
    usage: /name [付けたい名前:指定なしの場合は削除]
    aliases: [nm]
  tag:
    description: タグ登録ができます
    usage: /tag [付けたいタグ:指定なしの場合は削除]
    aliases: [tg]
  chest:
    description: チェスト操作コマンド
    usage: /chest <lock> (チェストを開ける事でロック/アンロック)
    aliases: [ch]
  price:
    description: 価格設定コマンド
    usage: /price <アイテム名> <価格>
    aliases: [pr]
  info:
    description: 123鯖情報を開く
    usage: /info (URLが出るのでクリックしてください)
    aliases: [if]
  map:
    description: 123鯖マップを開く
    usage: /map (URLが出るのでクリックしてください)
    aliases: [ma]
  shutdown:
    description: シャットダウンコマンド(コンソール専用)
    usage: /shutdown
    aliases: [sd]
  shop:
    description: ショップコマンド
    usage: /shop [あいまい検索キーワード]
    aliases: [sh]
  bi:
    description: ブロック情報クリックコマンド
    usage: /bi (モードON|OFF)
  pay:
    description: 支払コマンド
    usage: /pay <対象プレイヤー> <支払金額>
  ri:
    description: インベントリ消去コマンド
    usage: /ri
  rand:
    description: ランダム値表示コマンド
    usage: /rand <最小値> <最大値>
    aliases: [ra]
  area:
    description: エリア保護コマンド（1マス:1p）
    usage: /area <action(add|del)> <名前> ※指定なしの場合はキャンセル
    aliases: [ar]
  home:
    description: ホームポイント設定コマンド
    usage: /home [set] ※指定なしの場合はテレポート
    aliases: [ho]
