#
# plugin settings
#
name: KuroBase
version: ${project.version}
main: host.kuro.kurobase.KuroBase
api-version: 1.15
authors: [kuro-123]
description: Base plugin for 123 server culture spigot
website: http://kuro.host/
depend:
  - Citizens
  - KuroDiscord

commands:
  list:
    description: オンラインプレイヤーをリスト表示します
    usage: /list
    aliases: [li]
  name:
    description: ニックネーム登録ができます
    usage: /name [付けたい名前:指定なしの場合は削除]
    aliases: [nm]
  tag:
    description: タグ登録ができます
    usage: /tag [付けたいタグ:指定なしの場合は削除]
    aliases: [tg]
  chest:
    description: チェスト操作コマンド
    usage: /chest <lock> (チェストを開ける事でロック/アンロック)
    aliases: [ch]
  price:
    description: 価格設定コマンド
    usage: /price <アイテム名> <価格>
    aliases: [pr]
  info:
    description: 123鯖情報を開く
    usage: /info (URLが出るのでクリックしてください)
    aliases: [i]
  map:
    description: 123鯖マップを開く
    usage: /map (URLが出るのでクリックしてください)
    aliases: [ma]
  shutdown:
    description: シャットダウンコマンド(コンソール専用)
    usage: /shutdown
    aliases: [sd]
  shop:
    description: ショップコマンド
    usage: /shop [あいまい検索キーワード]
    aliases: [sh]
  bi:
    description: ブロック情報クリックコマンド
    usage: /bi (モードON|OFF)
  pay:
    description: 支払コマンド
    usage: /pay <対象プレイヤー> <支払金額>
  ri:
    description: インベントリ消去コマンド
    usage: /ri
  rand:
    description: ランダム値表示コマンド
    usage: /rand <最小値> <最大値>
    aliases: [ra]
  area:
    description: エリア保護コマンド（1マス:1p）
    usage: /area <action(add|del)> <名前> ※指定なしの場合はキャンセル
    aliases: [ar]
  home:
    description: ホームポイント設定コマンド
    usage: /home [set|del] ※指定なしの場合はテレポート
    aliases: [ho]
  creative:
    description: クリエになるコマンド
    usage: /creative (/c)
    aliases: [c]
  survival:
    description: サバイバルになるコマンド
    usage: /survival (/s)
    aliases: [s]
  sel:
    description: 選択コマンド（２点選択）
    usage: /sel
  set:
    description: ブロック設定コマンド
    usage: /set <ブロック選択or入力>
  rep:
    description: ブロック置換コマンド
    usage: /rep <ブロック選択or入力>
  paste:
    description: 貼付モードコマンド
    usage: /paste
  buddy:
    description: バディー操作
    usage: /buddy < add | del | list | url | join | quit | revival > ..
    aliases: [b]
  ai:
    description: AI操作(鯖主コマンド)
    usage: /ai <AI選択>
    aliases: [a]
  rule:
    description: ルール操作(管理コマンド)
    usage: /rule <ルール選択> <ON|OFF>
  pvp:
    description: PVPモード切替
    usage: /pvp <ON|OFF>
